---
AWSTemplateFormatVersion: "2010-09-09"

Resources:

  # ====== BEGIN STATIC SITE ======

  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mattb.tech
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: mattb.tech
      SubjectAlternativeNames:
      - www.mattb.tech
      - mattbenton.co.uk
      - www.mattbenton.co.uk
      - lionsmane.co.uk
      - www.lionsmane.co.uk
  
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
        - mattb.tech
        DefaultRootObject: index.html
        Origins:
        - DomainName: "mattb.tech.s3-website-us-east-1.amazonaws.com"
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  # ====== END STATIC SITE ======

  # ====== BEGIN REDIRECT ======

  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: redirect-mattb-tech
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: mattb.tech
          Protocol: https

  WwwRedirectCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
        - www.mattb.tech
        - mattbenton.co.uk
        - www.mattbenton.co.uk
        - lionsmane.co.uk
        - www.lionsmane.co.uk
        Origins:
        - DomainName: "redirect-mattb-tech.s3-website-us-east-1.amazonaws.com"
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  # ===== END REDIRECT ======
  
  # ===== BEGIN DNS ======

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: mattb.tech.
      RecordSets:
      - Name: mattb.tech
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFrontDistribution.DomainName
      - Name: www.mattb.tech
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt WwwRedirectCloudFrontDistribution.DomainName
  
  MattBentonCoUkRoute53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: mattbenton.co.uk.
      RecordSets:
      - Name: mattbenton.co.uk
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt WwwRedirectCloudFrontDistribution.DomainName
      - Name: www.mattbenton.co.uk
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt WwwRedirectCloudFrontDistribution.DomainName

  LionsmaneCoUkRoute53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: lionsmane.co.uk.
      RecordSets:
      - Name: lionsmane.co.uk
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt WwwRedirectCloudFrontDistribution.DomainName
      - Name: www.lionsmane.co.uk
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt WwwRedirectCloudFrontDistribution.DomainName

  # ===== END DNS ======

  # ===== BEGIN LAMBDA ======
  
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mattb.tech-code

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "src/index.handler"
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Code:
        S3Bucket: mattb.tech-code
        S3Key: lambda.zip
      Runtime: "nodejs8.10"

  # ===== END LAMBDA ======

Outputs:
  CloudFrontDistribution:
    Description: Distribution ID for CloudFront
    Value: !Ref CloudFrontDistribution
    Export:
      Name: CloudFrontDistribution

