---
AWSTemplateFormatVersion: "2010-09-09"

Resources:

  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: photo.mattb.tech
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: mattb.tech
      SubjectAlternativeNames:
      - photo.mattb.tech
  
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
        - mattb.tech
        - photo.mattb.tech
        DefaultRootObject: index.html
        Origins:
        - DomainName: "photo.mattb.tech.s3-website-us-east-1.amazonaws.com"
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: mattb.tech.
      RecordSets:
      - Name: mattb.tech
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFrontDistribution.DomainName
      - Name: photo.mattb.tech
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFrontDistribution.DomainName

Outputs:
  CloudFrontDistribution:
    Description: The 
    Value: !Ref CloudFrontDistribution
    Export:
      Name: CloudFrontDistribution

